### ISSUE TITLE
"https://github.com/ToniRV/mesh_rviz_plugins" does not exist...

### ISSUE THREAD

**Issue by xhy3054** [MIT-SPARK/Kimera-VIO-ROS#1]
**Description:**
 the repository may be private now?

**Command:**
```
wstool update
```

**Console output:**
```

Exception caught during install: Error processing 'mesh_rviz_plugins' : [mesh_rviz_plugins] Checkout of https://github.com/ToniRV/mesh_rviz_plugins.git version master into /home/xhy/allros_ws/kimeravio_ws/src/mesh_rviz_plugins failed.

ERROR in config: Error processing 'mesh_rviz_plugins' : [mesh_rviz_plugins] Checkout of https://github.com/ToniRV/mesh_rviz_plugins.git version master into /home/xhy/allros_ws/kimeravio_ws/src/mesh_rviz_plugins failed.


```

**Additional files:**
Please attach all the files needed to reproduce the error.

Please give also the following information:
* SparkVio branch, tag or commit used
* GTSAM version used:
* OpenGV version used:
* OpenCV version used: type `opencv_version`
* Operating system and version (e.g. Ubuntu 16.04 or Windows 10): 
* Did you change the source code? (yes / no):

**Comment by ToniRV** [comment]
Done, thanks!
