### ISSUE TITLE
Catkin build error build/kimera_vio/testKimeraVIO: symbol lookup error 

### ISSUE THREAD

**Issue by Goldsaints** [MIT-SPARK/Kimera-VIO-ROS#137]
Thank you for your excellent work and I am very interested in it. I download your code and install it, but an error encountered.

**Command:**
```
ubuntu:~/catkin_vio/src$ catkin build
```

**Console output:**
```
/home/ben/catkin_vio/build/kimera_vio/testKimeraVIO: symbol lookup error: /home/ben/catkin_ws/devel/lib/libkimera_vio.so: undefined symbol: _ZNK5gtsam16NoiseModelFactor5printERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN5boost8functionIFS6_mEEE
CMake Error at /usr/share/cmake-3.10/Modules/GoogleTestAddTests.cmake:39 (message):
  Error running test executable.

    Path: '/home/ben/catkin_vio/build/kimera_vio/testKimeraVIO'
    Result: 127
    Output:
      

make[2]: *** [testKimeraVIO] Error 1
make[2]: *** Deleting file“testKimeraVIO”
make[1]: *** [CMakeFiles/testKimeraVIO.dir/all] Error 2
make: *** [all] Error 2
```
I get the dependencies of the project by
```
wstool merge Kimera-VIO-ROS/install/kimera_vio_ros_https.rosinstall
```

**Additional files:**
Please attach all the files needed to reproduce the error.

Please give also the following information:
* KimeraVIO branch, tag or commit used
* GTSAM version used:  by kimera_vio_ros_https.rosinstall
* OpenGV version used: by kimera_vio_ros_https.rosinstall
* OpenCV version used: by kimera_vio_ros_https.rosinstall
* Operating system and version (e.g. Ubuntu 16.04 or Windows 10): Ubuntu 18.04
* Did you change the source code? (yes / no): no

Could you tell me what the version of your cmake?  (My cmake's version is 3.10)

When I build project in Ubuntu16.04 and cmake-3.16, build Kimera-VIO successfully, but had error when build Kimera-VIO-ROS.
The mistakes are :
![2](https://user-images.githubusercontent.com/23075686/115266664-f8efc300-a16a-11eb-9274-5c24c325688f.png)

Could you help me solve it? Sincerely.

**Comment by Tumucin** [comment]
Hello

I have the same problem. Did you manage to solve system lookup error?

**Comment by Goldsaints** [comment]
> Hello
> 
> I have the same problem. Did you manage to solve system lookup error?

Sorry, not yet.

**Comment by Goldsaints** [comment]
> Hello
> 
> I have the same problem. Did you manage to solve system lookup error?
Sorry, not yet.

**Comment by mikwaluk** [comment]
Hi, I experienced the same problem, opened #138

**Comment by mikwaluk** [comment]
Figured out a solution, although not exactly sure if it's correct this way. But at least it works and Kimera produces the correct estimation :)

```
diff --git a/src/KimeraVioRos.cpp b/src/KimeraVioRos.cpp
index 68fb81d..dd6343c 100644
--- a/src/KimeraVioRos.cpp
+++ b/src/KimeraVioRos.cpp
@@ -121,15 +121,15 @@ bool KimeraVioRos::spin() {
     std::future<bool> data_provider_handle =
         std::async(std::launch::async,
                    &VIO::RosDataProviderInterface::spin,
-                   std::ref(*CHECK_NOTNULL(data_provider_.get())));
+                   CHECK_NOTNULL(data_provider_.get()));
     std::future<bool> vio_viz_handle =
         std::async(std::launch::async,
                    &VIO::Pipeline::spinViz,
-                   std::ref(*CHECK_NOTNULL(vio_pipeline_.get())));
+                   CHECK_NOTNULL(vio_pipeline_.get()));
     std::future<bool> vio_pipeline_handle =
         std::async(std::launch::async,
                    &VIO::Pipeline::spin,
-                   std::ref(*CHECK_NOTNULL(vio_pipeline_.get())));
+                   CHECK_NOTNULL(vio_pipeline_.get()));
```

**Comment by ToniRV** [comment]
@mikwaluk that should be the way to do it, feel free to open a PR and I'll merge asap!

**Comment by Abirami-Segar** [comment]
Hi 

I faced the same problem as you did while compiling the packages. I was not able to build Kimera_VIO_ROS. I added the suggestion you gave.. Even then, there seems to be error while building this particular package. Could you please help?
