### ISSUE TITLE
ERROR: cannot launch node of type [image_undistort/dense_stereo_node]: image_undistort

### ISSUE THREAD

**Issue by HongLouyemeng** [MIT-SPARK/Kimera-VIO-ROS#159]
command:   roslaunch kimera_vio_ros kimera_vio_ros_euroc.launch run_stereo_dense:=true
ERROR: cannot launch node of type [image_undistort/dense_stereo_node]: image_undistort
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/root/catkin_ws/src/catkin_simple
ROS path [2]=/root/catkin_ws/src/disparity_image_proc
ROS path [3]=/root/catkin_ws/src/eigen_catkin
ROS path [4]=/root/catkin_ws/src/gflags_catkin
ROS path [5]=/root/catkin_ws/src/glog_catkin
ROS path [6]=/root/catkin_ws/src/eigen_checks
ROS path [7]=/root/catkin_ws/src/gtsam
ROS path [8]=/root/catkin_ws/src/Kimera-RPGO
ROS path [9]=/root/catkin_ws/src/mesh_rviz_plugins
ROS path [10]=/root/catkin_ws/src/minkindr/minkindr
ROS path [11]=/root/catkin_ws/src/minkindr_ros/minkindr_conversions
ROS path [12]=/root/catkin_ws/src/opencv3_catkin
ROS path [13]=/root/catkin_ws/src/dbow2_catkin
ROS path [14]=/root/catkin_ws/src/opengv_catkin
ROS path [15]=/root/catkin_ws/src/Kimera-VIO
ROS path [16]=/root/catkin_ws/src/pose_graph_tools
ROS path [17]=/root/catkin_ws/src/Kimera-VIO-ROS
ROS path [18]=/root/catkin_ws/src/protobuf_catkin
ROS path [19]=/root/catkin_ws/src/voxblox/voxblox
ROS path [20]=/root/catkin_ws/src/Kimera-Semantics/kimera_semantics
ROS path [21]=/root/catkin_ws/src/voxblox/voxblox_msgs
ROS path [22]=/root/catkin_ws/src/voxblox/voxblox_rviz_plugin
ROS path [23]=/root/catkin_ws/src/voxblox/voxblox_ros
ROS path [24]=/root/catkin_ws/src/Kimera-Semantics/kimera_semantics_ros
ROS path [25]=/opt/ros/melodic/share

**Comment by ZFDD96** [comment]
Hi! I encounter the same problem. Could you tell me how do you solve this problem? Thanks.

**Comment by ZFDD96** [comment]
> Hi! I encounter the same problem. Could you tell me how do you solve this problem? Thanks.
Oh! I got it. There is not a package named image_undistort. When I build it using catkin, this problem is solved. And don't forget source setup.bash after build. You can using command 'catkin build image_undistort' in your catkin workspace 'catkin_ws' before you download a image_undistort package in your catkin src folder. This package can be downloaded from github.

**Comment by HongLouyemeng** [comment]
> > Hi! I encounter the same problem. Could you tell me how do you solve this problem? Thanks.
> > Oh! I got it. There is not a package named image_undistort. When I build it using catkin, this problem is solved. And don't forget source setup.bash after build. You can using command 'catkin build image_undistort' in your catkin workspace 'catkin_ws' before you download a image_undistort package in your catkin src folder. This package can be downloaded from github.

Thank you for your reply. I forgot how I solved this problem. I should set it to off.
