### ISSUE TITLE
For frame [imu4]: Frame [imu4] does not exist 

### ISSUE THREAD

**Issue by omarosamahu** [MIT-SPARK/Kimera-VIO-ROS#16]
After using "$rostopic echo /imu0" I got the following errrors the orientation in 'x','y','z','w' don't change 

![imu_err](https://user-images.githubusercontent.com/8967083/69238219-23b5a080-0ba0-11ea-8f29-bf9746df8426.png)
![imu_frame_err](https://user-images.githubusercontent.com/8967083/69238222-244e3700-0ba0-11ea-9b5b-1aaf139e5017.png)

**Comment by ToniRV** [comment]
Hi @omarosamahu,
That is expected, since an IMU does not provide absolute orientation information but angular velocities (which can then be integrated over time to get relative orientation).
