### ISSUE TITLE
[C++11] catkin build errors

### ISSUE THREAD

**Issue by mzahana** [MIT-SPARK/Kimera-VIO-ROS#23]
**Description:**
I get build errors when building  `pose_graph_tools` and `kimera_rviz_markers`

**Command:**
```
catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release
```
error fixed by adding the following in their corresponding CMakeLists.txt
```
add_compile_options(-std=c++11)
```

**Comment by violetteavi** [comment]
It looks like you resolved this yourself-- closing for now.
