### ISSUE TITLE
Realsense & Mynteye S launch files are unavailable (linked to github.mit.edu)

### ISSUE THREAD

**Issue by K0stIa** [MIT-SPARK/Kimera-VIO-ROS#3]
So are  Kalibr2KimeraVIO-pinhole-equi and Kalibr2KimeraVIO-pinhole-radtan files from mynteye [guide](https://github.com/MIT-SPARK/Kimera-VIO-ROS/blob/master/docs/hardware_setup.md#setup-1)

all rviz links from Testing [section](https://github.com/MIT-SPARK/Kimera-VIO-ROS/blob/master/docs/hardware_setup.md#testing-1) are unavailable due to same reason.

-K.

**Comment by ToniRV** [comment]
Fixing in #7

**Comment by ToniRV** [comment]
These two scripts were merged into one: https://github.com/MIT-SPARK/Kimera-VIO/blob/master/kalibr/config2sparkvio.py

**Comment by ToniRV** [comment]
Done!

**Comment by logindiamant** [comment]
Where can I download kitti_2011_09_26_drive_0005_unsynced.bag with MYNT EYE and RealSense data?
