### ISSUE TITLE
Porting to ROS2

### ISSUE THREAD

**Issue by ruffsl** [MIT-SPARK/Kimera-VIO-ROS#39]
I'd like to ask if there would be any interest in porting the Kimera ROS wrapper to ROS2. I'm currently in progress of developing the port, and am at a stage where I'd like to reach out to collaborate further. I have a compiling and running prototype modeled after the existing ROS1 wrapper, but included a number of performance improvement to take advantage on newer paradigms and features in ROS2. Areas I'd like to extend include:

* composable nodes so both kimera and sensor nodes can be co-located in the same process
  * https://index.ros.org/doc/ros2/Tutorials/Composition
* use of zero copy transport or loaned messages when composing nodes is not applicable
  * https://github.com/ros2/rmw_iceoryx
* use of multithreaded executors for reducing message callback latency
  * https://index.ros.org/doc/ros2/Tutorials/Intra-Process-Communication
* SROS2 Security, etc...

References:
* https://index.ros.org/doc/ros2/
* http://design.ros2.org/

**Comment by ToniRV** [comment]
Hi @ruffsl, I should read more about ROS2 as I've only heard good things about it so far but I am not fully aware of its potential.
I am definitely willing to help on this effort since it will help making Kimera run even faster :+1: 
I'll have a look at the references you mention and the code changes you propose. 
Thank you very much!

**Comment by ruffsl** [comment]
Awsome! I'm just now calibrating a realsense D435i, and I believe the example realsense config in the package is missing sample camera yaml files. This perhaps explains why non of the output callbacks are being triggered, though input fill callbacks are being called. I'll also update the .repos file for the draft PR so the Dockerfile builds, as I've moved the branch names around before opening the draft.

**Comment by ToniRV** [comment]
I'm preparing a new push with fixed output callbacks.

**Comment by ruffsl** [comment]
> I'm preparing a new push with fixed output callbacks.

Is this pointed at upstream in kimera_vio or to the draft PR pointed at kimera_vio_ros?

**Comment by ToniRV** [comment]
Upstream in kimera_vio.

**Comment by ruffsl** [comment]
Current progress can be tracked at my PR over at our new repo: https://github.com/MIT-SPARK/Kimera-VIO-ROS2/pull/5
