### ISSUE TITLE
ERROR Did not load frame id

### ISSUE THREAD

**Issue by amburkoff** [MIT-SPARK/Kimera-VIO-ROS#42]
The next launcher file gives an error:
$ roslaunch kimera_vio_ros kimera_ros_kitti.launch

WARNING: Package name "KimeraRPGO" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
... logging to /home/amburkoff/.ros/log/0d735e06-4cdd-11ea-a0db-34e12de90b0b/roslaunch-MSI-28614.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

WARNING: Package name "KimeraRPGO" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
started roslaunch server http://localhost:39089/

SUMMARY
========

PARAMETERS
 * /kimera_vio_ros/kimera_vio_ros/base_link_frame_id: base_link
 * /kimera_vio_ros/kimera_vio_ros/left_cam_frame_id: left_cam
 * /kimera_vio_ros/kimera_vio_ros/map_frame_id: map
 * /kimera_vio_ros/kimera_vio_ros/mono_ransac_threshold: 30
 * /kimera_vio_ros/kimera_vio_ros/online_run: True
 * /kimera_vio_ros/kimera_vio_ros/position_det_threshold: 0.3
 * /kimera_vio_ros/kimera_vio_ros/right_cam_frame_id: right_cam
 * /kimera_vio_ros/kimera_vio_ros/stereo_ransac_threshold: 20
 * /kimera_vio_ros/kimera_vio_ros/use_lcd: False
 * /kimera_vio_ros/kimera_vio_ros/velocity_det_threshold: 0.1
 * /kimera_vio_ros/kimera_vio_ros/world_frame_id: world
 * /kimera_vio_ros/posegraph_viewer/frame_id: world
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /use_sim_time: True

NODES
  /
    velo_link_broadcaster (tf/static_transform_publisher)
  /kimera_vio_ros/
    kimera_vio_ros (kimera_vio_ros/kimera_vio_ros)
    posegraph_viewer (pose_graph_tools/visualizer_node)

ROS_MASTER_URI=http://localhost:11311

WARNING: Package name "KimeraRPGO" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[kimera_vio_ros/kimera_vio_ros-1]: started with pid [28629]
process[kimera_vio_ros/posegraph_viewer-2]: started with pid [28630]
process[velo_link_broadcaster-3]: started with pid [28631]
[ INFO] [1581432298.134822116]: Initializing pose graph visualizer
**[ERROR] [1581432298.135850744]: Did not load frame id
F0211 17:44:58.223088 28629 YamlParser.h:79] Cannot open file in parseYAML: /home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/LeftCameraParams.yaml (remember that the first line should be: %YAML:1.0)**
*** Check failure stack trace: ***
    @     0x7f854ca1fb0d  google::LogMessage::Fail()
    @     0x7f854ca219b1  google::LogMessage::SendToLog()
    @     0x7f854ca1f63d  google::LogMessage::Flush()
    @     0x7f854ca22369  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f854ab41b12  VIO::CameraParams::parseYAML()
    @     0x7f854ab1a2ca  VIO::parsePipelineParams<>()
    @     0x7f854ab1a64c  VIO::DataProviderInterface::parseCameraParams()
    @     0x7f854ab1a6ad  VIO::DataProviderInterface::parseParams()
    @     0x7f854ab1ac09  VIO::DataProviderInterface::DataProviderInterface()
    @     0x7f854ab1b185  VIO::DataProviderInterface::DataProviderInterface()
    @     0x55b959b5aa59  (unknown)
    @     0x55b959b7b48a  (unknown)
    @     0x55b959b4542a  (unknown)
    @     0x7f85492b4b97  __libc_start_main
    @     0x55b959b4824a  (unknown)
[**kimera_vio_ros/kimera_vio_ros-1] process has died [pid 28629, exit code -6, cmd /home/amburkoff/cb_ws/devel/lib/kimera_vio_ros/kimera_vio_ros --left_cam_params_path=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/LeftCameraParams.yaml   --right_cam_params_path=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/RightCameraParams.yaml   --imu_params_path=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/ImuParams.yaml   --backend_params_path=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/regularVioParameters.yaml   --frontend_params_path=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/trackerParameters.yaml   --use_lcd=false   --lcd_params_path=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/LCDParameters.yaml   --vocabulary_path=/home/amburkoff/cb_ws/src/Kimera-VIO/vocabulary/ORBvoc.yml   --flagfile=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/flags/Mesher.flags   --flagfile=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/flags/VioBackEnd.flags   --flagfile=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/flags/RegularVioBackEnd.flags   --flagfile=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/param/Kitti/flags/Visualizer3D.flags   --logtostderr=1 --colorlogtostderr=1 --log_prefix=1 --v=0 --backend_type=1 --log_output=false --output_path=/home/amburkoff/cb_ws/src/Kimera-VIO-ROS/output_logs/ --visualize=false --parallel_run=True left_cam:=/kitti/camera_gray_left/image_raw right_cam:=/kitti/camera_gray_right/image_raw imu:=/kitti/oxts/imu reinit_flag:=reinit_flag reinit_pose:=reinit_pose odometry:=odometry resiliency:=resiliency imu_bias:=imu_bias optimized_trajectory:=optimized_trajectory pose_graph:=pose_graph mesh:=mesh frontend_stats:=frontend_stats debug_mesh_img:=debug_mesh_img time_horizon_pointcloud:=time_horizon_pointcloud __name:=kimera_vio_ros __log:=/home/amburkoff/.ros/log/0d735e06-4cdd-11ea-a0db-34e12de90b0b/kimera_vio_ros-kimera_vio_ros-1.log].
log file: /home/amburkoff/.ros/log/0d735e06-4cdd-11ea-a0db-34e12de90b0b/kimera_vio_ros-kimera_vio_ros-1*.log**

* Operating system and version: Ubuntu 18.04 
* Did you change the source code: no

**Comment by ToniRV** [comment]
@amburkoff sorry we are not actively supporting Kitti dataset right now as we had some issues getting reliable IMU data from the dataset.
I would suggest you try with the Euroc dataset for now (the parameters for Kitti are outdated).
