### ISSUE TITLE
How to enable Fast Multi-Frame Metric Reconstruction display in rviz?

### ISSUE THREAD

**Issue by amburkoff** [MIT-SPARK/Kimera-VIO-ROS#44]
I launch roslaunch kimera_vio_ros kimera_ros_euroc.launch
1. How to enable Fast Multi-Frame Metric Reconstruction display in rviz?
2. Is it possible to make Slow Global Metric Dense Reconstruction without semantic information?

**Comment by ToniRV** [comment]
1. I did not have time to implement this one.
2. Yes, but I need to document how to do that (let me do this in Kimera-Semantics repo though).

**Comment by ToniRV** [comment]
For 2. Checkout https://github.com/MIT-SPARK/Kimera-Semantics/issues/7
