### ISSUE TITLE
Example congif open access

### ISSUE THREAD

**Issue by secondsensei** [MIT-SPARK/Kimera-VIO-ROS#6]
Please give an open-source link to the [example configurations](https://github.com/MIT-SPARK/Kimera-VIO-ROS/blob/master/docs/hardware_setup.md#testing) that are currently hosted in an MIT repository that require an existing account for access. Thanks, great work.

**Comment by ToniRV** [comment]
Fixing in #7

**Comment by ToniRV** [comment]
Done!
