### ISSUE TITLE
RGB-D images instead of stereo

### ISSUE THREAD

**Issue by eliabntt** [MIT-SPARK/Kimera-VIO-ROS#86]
Hi, I would like to know if it is possible to use your VIO with RGBD images instead of stereo ones.

Specifically, I'm currently running a simulation (in gazebo) with a D435i. I've seen that you have a launch file for that kind of camera but my IR images are already rectified and seem identical despite the different POV stated in the .xacro but I have available RGB and depth images already rectified.

**Comment by moksh019** [comment]
Hi @eliabntt 
May you let me know how you connected kimera with Gazebo?
thanks

**Comment by eliabntt** [comment]
Not done this, sorry
